### ISSUE TITLE
Meeting Notes from 3/21/2015 with Lee Asher

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#32]
Lee Asher   leeasher.com
Father is a Magician

Creates "effects" for other magicians
Sells via .pdf and movies?
Lectures to other magicians

Penguinmagic.com

Routine builder is great

List of questions, based on criteria.

Instead of being a suggestion from the computer, suggestion from the "old wise master" that gives it a persona for the site.

===== User, "Magician"

Name
Location (City / State / Country)
Age
Bio
Photo
Type of Magic Interest (cards, silk, etc)
Influences
What's on your bookshelf / in your video collection?  Which did you last read / watch?
Favorite deck of cards?
Do you like to collect magic?
How large is your professional crew?
What other sites do you frequent?
Affiliations / Associations / Local Clubs & Groups
Awards / Accolades / Competitions?
Last attended lecture / convention?
What's your favorite magic shop online/offline?
Years of Experience
Last trick performed / when?
Crowning moment?
Favorite YouTube Magic Video?
Largest show performed?
How often do you perform per week?
Do you want to find out about new magic?
Level of Experience (pre-built list)

-- Neophyte (newbie)
-- Enthusiast
-- Hobbyist
-- Historian
-- Collector
-- Semi-professional (does a few shows / year)
-- Professional (makes an earning)

Social Media (fb, g+, twit, weibo)
Personal Website

===== Routine (smaller parts)  
Effects:  http://geniimagazine.com/wiki/index.php/Effect_Classification
Methods:  Description
Handling:  Details

Name
Type (pre-built list?)
Suggested skill level
Description
Length
Audience Involvement (yes / no)
Materials (inspected?)
User keeps something at the end
Opener / Middle / Closer
Attribution (source)?  Proper attribution. Date of first performed.
Venue 0-50 close up 50-100 stand up 100-250 stage 250+ grand illusion
Prep Time (instant / short / long)
Cost of Materials
Reset time
Space requirement (pockets / small / large / gargantuan)

===== Sets

Name of Set
Name / Photo of Creator
Skill level of creator
Rating (community rating)
Length
Venue
Story / Plot
Array of Effects

Don't repeat Routines / Effects
Set for Money
Build something outside of the comfort zone (wildcard)
Short / Medium / Long
Type of Venue suggestion
Suggest if a specific prop is given

Community curators as a future thing

Effects Page - shortlist of things at the top, ingredients directly at the top
- Materials
- Description
- Type
- Cost
  Collapsed information

Popularity of the effect?
More popular the trick, the more it will be used by hobby/enthusiast

**Comment by davidkneely** [comment]
Lee stressed the importance of listing supplies far more than I thought he would.  

**Monetization Idea:** Hot link common supplies to Amazon with an associate's id. :moneybag:

**Comment by marknelsonengineer** [comment]
It's his business...  and it is very important.  I wouldn't expect, however, to find these sorts of things on Amazon.  When it comes time to seed the dataset, we can troll through Theory11, Penguin, Illusionist, Grand Illusions as well as the personal websites of Lee Asher, Wayne Houchin, David Regal, Eric Jones and others.  I hope to have a healthy set of effects seeded in the database.

**Comment by marknelsonengineer** [comment]
Lee's initial comment:  "It's really cool".

Penguin Magic did a Build your Act app a few years ago, but it was not a commercial success, probably due to inadequate marketing and product positioning.

Fields for the Magician (User) entity:
Type (Newbie, Enthusiast / Family magic, Magic Club / Hobbiest, Semi-Professional, Professional (you make a living at it)
Age
Location
Bio
Kind of Magic you're into
What's on your bookshelf?
Who are your influences?
What magic forums do you frequent?
Do you belong to any magic organizations (IBM, SAM, etc.)?
What is the last routine you performed and when?
What is your favorite YouTube magic video?
Do you want to hear about new magic?
Have you ever busked (done street magic?)
What is the largest show you've ever done?
On average, the number of performances per year?
What is your home magic store?
Have you won any awards?
Are you preparing for a show?
What is the last book/DVD you read/watched?
Your favorite deck?
What size of coins do you work with?
Do you have any magic-related collections?
What is the last convention or lecture you attended?

=-=-=-=-=-=-=-=-
Attributes related to the Routine entity
What is the Effect?
Describe the Method.
What is the Plot? -- see taxonomy.
Describe the Handling.
How long is the routine?
Does it require spectators?  How many?
Materials:
  Name / Inspectable / Consumed
Any takeaways / keepsakes
Is the routine an opener? Middler? Closer?
To whom can you attribute the original creator of the routine?
Who introduced you to the routine?
<< Star system the assess the quality of the attribution >>

Venue
0-50 = Close-up
50-100 = Parlor
100-300 = Stage
300+ = Grand Illusion

Does it instantly reset?
What is the prep time?
Does it consume materials?
What is the space requirement?
What is the skill level to perform?
Can this routine be shared to other PlayWithMagic users?

=-=-=-=-=-=-=-=-
Attributes related to the Set entity
Venue

Computed values related to the Set entity
Length
Cost
Materials

Search values related to finding routines for a set
Random
Comfort Zone
Routines with high ratings from Professional magicians
Have a professional suggest a set for you

Business rules related to sets:
Be sure the routines in the set don't repeat an effect.  If your first routine emphasizes a torn-and-restored effect, then don't close with the same effect -- you've already established that you can do that.

**Comment by marknelsonengineer** [comment]
Closed
